name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -D
      - run: npm run pack
      - uses: actions/upload-artifact@v2
        with:
          name: "Yatsugi for ${{ matrix.os }}"
          path: ./bin/
