name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -D
      - run: npm run pack
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "./README.md"
          target: "./bin/README.md"
      - uses: actions/upload-artifact@v2
        with:
          name: "Yatsugi-for-${{ matrix.os }}"
          path: ./bin/
