name: Publish

on:
  push:
    branches: [master, feature/ci/*]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          lfs: true
      - run: git lfs checkout
        name: Checkout LFS
      - uses: actions/setup-node@v2-beta
        name: Setup Node.js
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm install -D
        name: Install dependency packages
      - run: npm run pack
        name: Pack this app
      - run: copy ./README.md ./bin/README.md
        name: Copy README (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
      - run: cp ./README.md ./bin/README.md
        name: Copy README (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: "Yatsugi-for-${{ matrix.os }}"
          path: ./bin/
